services:
  redis:
    image: redis:7-alpine
    container_name: dblledger_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    container_name: dblledger_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
